### ISSUE TITLE
支持一下,后续可以对接4吗

### ISSUE THREAD

**Issue by Mxa-g** [liuw5367/chatgpt-asr-tts#2]

**Comment by Mxa-g** [comment]
环境代理也有问题

**Comment by Mxa-g** [comment]
TypeError: fetch failed

**Comment by Mxa-g** [comment]
看了下可以了，是没有生成语音KEY导致

**Comment by Mxa-g** [comment]
图像生成就空白页面了

**Comment by Mxa-g** [comment]
不能翻译中国语言,画图好了

**Comment by Mxa-g** [comment]
有个BUG 语音KEY没有用或者设置了没有额度就耽误GPT正常聊天

**Comment by liuw5367** [comment]
> TypeError: fetch failed

这个我也遇到了，在 vercel 的log里能看到 超时的错误。我也看到别人有遇到这个问题。
给我的感觉像是 openai 做了限制似的，正经去问就没有问题，把内容描述的正式一点就可以了

**Comment by liuw5367** [comment]
> 有个BUG 语音KEY没有用或者设置了没有额度就耽误GPT正常聊天

语音我刚试了，是可以用的，填上 key 和 secret，就会出现 asr 和 tts 的按钮

**Comment by liuw5367** [comment]
环境变量的配置有点问题，部署的时候无效，我需要再修改一下。页面中设置 key 是正常的

**Comment by liuw5367** [comment]
> 图像生成就空白页面了

图像应该是因为加载特别慢。 按钮 loading 结束后要好久才能出来图片，不知道是不是我忘了不够好

**Comment by Mxa-g** [comment]
[图片正常，聊天还是转圈圈不回复

**Comment by Mxa-g** [comment]
填上 key 和 secret，是显示 asr 和 tts 的按钮 点击录音启动失败

**Comment by liuw5367** [comment]
> [图片正常，聊天还是转圈圈不回复

你问的是什么？ 比如我问 ‘人工智能有哪些种类？’是可以回复的。
你是所有的都不回复吗？
KEY 有没有问题

**Comment by liuw5367** [comment]
> 填上 key 和 secret，是显示 asr 和 tts 的按钮 点击录音启动失败

可以打开浏览器的开发者工具，看一下网络里是什么报错。语音是 socket 请求

**Comment by Mxa-g** [comment]
我本地开的VPN 我问你好 你在干嘛 /api/generate接口发出去 没有返回

**Comment by Mxa-g** [comment]
方便加个联系方式嘛

**Comment by Mxa-g** [comment]
key没有问题，图片都能正常，余额也正常，聊天的话问什么都不返回 转圈圈  接口200 也不返回

**Comment by Mxa-g** [comment]
[](https://i.ibb.co/7VwPCSj/1.png)

**Comment by Mxa-g** [comment]
[https://i.ibb.co/7VwPCSj/1.png](https://i.ibb.co/7VwPCSj/1.png)

**Comment by Mxa-g** [comment]
没在vercel里部署，在本地vscode跑的

**Comment by liuw5367** [comment]
> [https://i.ibb.co/7VwPCSj/1.png](https://i.ibb.co/7VwPCSj/1.png)

不要发“你好”，可以发“你好呀，请介绍一下自己”试试。 我使用的时候发现，如果问题很短就不会有回复。 问句要长一些，要正式一些，描述的清楚一点。


本地起的服务，可以看一下终端，如果报错会有日志。 我之前试过一次，很长时间就是不报错，一直在等待，就没再试。

这个问题无解，因为是直接调用的 openai 的接口，不反回结果也不是代码的问题……

**Comment by Mxa-g** [comment]
问一下哈，就是录音可以，但是播放提示合成遇到点问题，请稍后再试~ 是什么原因呢 套餐不对吗

**Comment by liuw5367** [comment]
> 问一下哈，就是录音可以，但是播放提示合成遇到点问题，请稍后再试~ 是什么原因呢 套餐不对吗

不清楚 🤦‍♂️ 我也不大熟。可以看一下浏览器的网络面板，看看怎么返回的。我记得新注册的号，是可以领几天的免费额度的

**Comment by liuw5367** [comment]
> 还有模型 改gtp-4支持么 现在没有4的key测试 先问下

不清楚，没测过…… 按说直接改模型是能用的，因为文档里写的 model 参数是支持 gpt-4 的

**Comment by Mxa-g** [comment]
本地挂VPN就没成功过，放弃你这个了，也不支持代理

**Comment by Mxa-g** [comment]
但是还是支持你的

**Comment by liuw5367** [comment]
> 本地挂VPN就没成功过，放弃你这个了，也不支持代理

好的，再见。可以试试那些 star 高的，好像有支持代理的。这个项目毕竟是为了符合我自己的需求做的。

我个人用的话，
1. 部署在 vercel 免去 openai 翻墙
2. vercel  在国内打不开，自己买一个便宜的域名，绑在上面
这样就能免科学上网了...
