### ISSUE TITLE
环境变量读取失败

### ISSUE THREAD

**Issue by liuw5367** [liuw5367/chatgpt-asr-tts#3]
环境变量读取失败，添加 public 前缀可以读取。astro 的文档中服务端是不要加 public 的，而且用另一个项目测试读取环境变量又是正常的，很奇怪

**Comment by Mxa-g** [comment]
export const APP_CONFIG = {
  USER_ID: "abcdefg12345",
  UDID: "abcdefg12345",
};
这俩？

**Comment by Mxa-g** [comment]
大佬,提示context_length_exceeded
此模型的最大上下文长度为 4097 个标记。但是，您请求了 4100 个令牌（消息中有 18 个，完成中有 4082 个）。请减少消息或完成的长度。 是因为啥

**Comment by liuw5367** [comment]
> export const APP_CONFIG = { USER_ID: "abcdefg12345", UDID: "abcdefg12345", }; 这俩？

是环境变量，不是常量。
文档：https://docs.astro.build/zh-cn/guides/environment-variables/

使用 `import vercel from "@astrojs/vercel/serverless" ` 是正常的。
使用 `import vercel from "@astrojs/vercel/edge" ` 不知道为什么不能加载非 `PUBLIC_` 开头的环境变量

**Comment by liuw5367** [comment]
> 大佬,提示context_length_exceeded 此模型的最大上下文长度为 4097 个标记。但是，您请求了 4100 个令牌（消息中有 18 个，完成中有 4082 个）。请减少消息或完成的长度。 是因为啥

可能是 buildRequestMessages 函数里计算 max_tokens 没算对。post 请求时可以删掉该参数

**Comment by liuw5367** [comment]
> 大佬,提示context_length_exceeded 此模型的最大上下文长度为 4097 个标记。但是，您请求了 4100 个令牌（消息中有 18 个，完成中有 4082 个）。请减少消息或完成的长度。 是因为啥

已修复 🤦‍♂️

**Comment by Mxa-g** [comment]
请问下，一个KEY支持多少用户访问？环境配置我用ver部署可用 没有输入KEY的清空下 默认可以新增多个KEY随机调用吗

**Comment by liuw5367** [comment]
> 请问下，一个KEY支持多少用户访问？环境配置我用ver部署可用 没有输入KEY的清空下 默认可以新增多个KEY随机调用吗

同一个账号，好像同时只能有一个请求吧，OpenAI好像有限制，这个我不是很确定。暂不考虑多个KEY的情况，现在应用还不是很完善，没精力搞这些，个人使用来说，应该一个KEY就可以了。
提供个玩笑的思路：Vercel 上多绑定几个子域名，在不同的标签页打开，然后填入不同的KEY 😂  域名不同就能分开缓存 Key 了

**Comment by Mxa-g** [comment]
哈哈哈啊哈哈

**Comment by Mxa-g** [comment]
export const APP_CONFIG = {
USER_ID: "abcdefg12345",
UDID: "abcdefg12345",
};
这是什么？

**Comment by liuw5367** [comment]
> export const APP_CONFIG = {
> 
> USER_ID: "abcdefg12345",
> 
> UDID: "abcdefg12345",
> 
> };
> 
> 这是什么？

unisound 语音用来区分用户请求的吧，我从官网demo里复制的，然后改了个值。

语音这块只是顺手做的，不是主动能，说实在的没啥动力更新完善，因为自己用不到

**Comment by liuw5367** [comment]
应该是 astro 的bug。
我测试的时候发现，如果没有 PUBLIC_ 前缀，react + @astrojs/vercel/edge 无法在边缘函数中获取环境变量。本地运行正常，问题仅在部署到 Vercel 时出现。在 Vercel 上部署 solidjs + @astrojs/vercel/edge、react + @astrojs/vercel/serverless 也是正常的。
