### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by Mxa-g** [liuw5367/chatgpt-asr-tts#6]
1.页面上点代码区域的复制按钮 粘贴后单引号会变成小于号  问的问题是：pythone怎么执行shell脚本
2.文本框输入内容的时候 尖括号的内容 不展示，但实际会发送过去   问的问题是<test>
3.用环境变量设置的key速度很快，如果在页面上单独设置自己的key速度很慢

**Comment by liuw5367** [comment]
感谢反馈

我这几天使用的时候发现也很慢，但是应该和环境变量没关系，调用的都是同一个接口，是不是因为不是付费用户的原因，现在给降速了  🤦‍♂️

第二条问的内容是啥呀

**Comment by liuw5367** [comment]
知道 1、2是什么问题了。这两天跟着 nextjs 一块更新。
第三条调用的是同一个接口，接口中没有传 key 就会使用环境变量。 不哪里有区别... 就算真有区别又能怎么改的 🤦‍♂️

**Comment by Mxa-g** [comment]
OK~ 因为是key与key之间的区别 5美金的key有限制吧

**Comment by liuw5367** [comment]
> OK~ 因为是key与key之间的区别 5美金的key有限制吧

不知道呀。我用的时候就感觉时快时慢的....

**Comment by liuw5367** [comment]
> 1.页面上点代码区域的复制按钮 粘贴后单引号会变成小于号 问的问题是：pythone怎么执行shell脚本 2.文本框输入内容的时候 尖括号的内容 不展示，但实际会发送过去 问的问题是 3.用环境变量设置的key速度很快，如果在页面上单独设置自己的key速度很慢


主分支已修复
