### ISSUE TITLE
Windows 端 Firefox 無法輸入中文

### ISSUE THREAD

**Issue by ChiesiMario** [liuw5367/chatgpt-asr-tts#8]
Chrome 系瀏覽器正常，Firefox 輸入中文變成空格或輸入的拼音。粘貼中文可以。

**Comment by liuw5367** [comment]
没用过firefox，等有空我试试

**Comment by liuw5367** [comment]
刚看到 issue，也不清楚 github 是啥情况，有时候能收到邮件提醒，有时候又没有

**Comment by liuw5367** [comment]
在 mac 上的 Firefox 上复现，已修复。在 Windows 上应该一样
